better deployment logic that also handles local deployments

diff --git a/jee/servlet/simplest/bin/deployment-logic b/jee/servlet/simplest/bin/deployment-logic
--- a/jee/servlet/simplest/bin/deployment-logic
+++ b/jee/servlet/simplest/bin/deployment-logic
@@ -10,37 +10,53 @@
 #   undeploy
 #
 
-# space separated list of deployment servers. One is fine.
-deployment_servers="172.20.2.42 172.20.2.43"
+# space separated list of deployment servers. One is fine. For local deployment, 
+# use "local"
+#deployment_servers="172.20.2.42 172.20.2.43"
+deployment_servers="local"
 
 artifact_file_name=servlet-example.war
 deployment_user=wildfly
-deployment_path=/opt/wildfly/profiles/ap/deployments
+#deployment_path=/opt/wildfly/profiles/ap/deployments
+deployment_path=${JBOSS_HOME}/profiles/undertow/deployments
+
 
 function deploy() {
 
     local artifact_file=$1 # absolute path
-    local deployment_user=$2
-    local deployment_server=$3
+    local deployment_server=$2
+    local deployment_user=$3
     local deployment_path=$4
 
-    scp ${artifact_file} ${deployment_user}@${deployment_server}:${deployment_path} && \
-        echo "$(basename ${artifact_file}) successfully deployed in ${deployment_user}@${deployment_server}:${deployment_path}" || \
-        { echo "deployment failed" 1>&2; exit 1; }
+    if [ "${deployment_server}" = "local" ]; then
+        cp ${artifact_file} ${deployment_path} && \
+            echo "$(basename ${artifact_file}) successfully deployed in ${deployment_path}" || \
+            { echo "deployment failed" 1>&2; exit 1; }
+    else
+        scp ${artifact_file} ${deployment_user}@${deployment_server}:${deployment_path} && \
+            echo "$(basename ${artifact_file}) successfully deployed in ${deployment_user}@${deployment_server}:${deployment_path}" || \
+            { echo "deployment failed" 1>&2; exit 1; }
+    fi
 }
 
 function undeploy() {
 
     local artifact_file=$1 # absolute path (even if does not exist)
-    local deployment_user=$2
-    local deployment_server=$3
+    local deployment_server=$2
+    local deployment_user=$3
     local deployment_path=$4
 
     local artifact_file_name=$(basename ${artifact_file})
 
-    ssh ${deployment_user}@${deployment_server} rm ${deployment_path}/${artifact_file_name} && \
-        echo "${artifact_file_name} successfully removed from ${deployment_user}@${deployment_server}:${deployment_path}" || \
-        { echo "undeployment failed" 1>&2; exit 1; }
+    if [ "${deployment_server}" = "local" ]; then
+        rm ${deployment_path}/${artifact_file_name} && \
+            echo "${artifact_file_name} successfully removed from ${deployment_path}" || \
+            { echo "undeployment failed" 1>&2; exit 1; }
+    else
+        ssh ${deployment_user}@${deployment_server} rm ${deployment_path}/${artifact_file_name} && \
+            echo "${artifact_file_name} successfully removed from ${deployment_user}@${deployment_server}:${deployment_path}" || \
+            { echo "undeployment failed" 1>&2; exit 1; }
+    fi
 }
 
 function main() {
@@ -52,7 +68,7 @@ function main() {
     [ "${command}" = "deploy" -a ! -f ${artifact_file} ] && { echo "${artifact_file_name} not built" 1>&2; exit 1; }
 
     for ds in ${deployment_servers}; do
-        ${command} ${artifact_file} ${deployment_user} ${ds} ${deployment_path}
+        ${command} ${artifact_file} ${ds} ${deployment_user} ${deployment_path}
     done
 }
 
